name: Pull Request Testflow
on:
  pull_request:
    types:
    - opened
    - reopened
    branches:
    - 'feature/**'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
