name: Format check on Pull Request
on: 
 pull_request:
  types: [ "opened", "edited" ]
  branches: [ "develop", "master", "main" ]
  paths:
      - "**.cs"
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
